import { Fragment } from "react";
import Head from "next/head";
import WhoWeAre from "../components/WhoWeAre/WhoWeAre";
import Advantages from "../components/Advantages/Advantages";
import OurSection from "../components/OurSection/OurSection";
import SuccessfulBusiness from "../components/SuccessfulBusiness/SuccessfulBusiness";

export default function Home() {
	return (
		<Fragment>
			<Head>
				<title>S-Tips</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Advantages />
			<WhoWeAre />
			<SuccessfulBusiness />
			<OurSection />
		</Fragment>
	);
}
